### ISSUE TITLE
Terminal doesn't accept input

### ISSUE THREAD

**Issue by billmarriott-deriv** [ksysoev/wsget#2]
In request mode, if you enter an invalid request, program exits and you can't use the terminal anymore.

e.g. 
```
./wsget -u 'wss://<server>'
Connection Mode: Press ESC to enter Request mode
Request Mode: Type your API request and press Ctrl+S to send it. Press ESC to cancel request
sfdsf   <ctrl+S>
Connection Mode: Press ESC to enter Request mode
sfdsf

2023/10/23 11:37:26 Fail to read from WS connection:EOF
```
Now you can't type anything.

**Comment by ksysoev** [comment]
@billmarriott-deriv what do you mean by not being able to use the terminal anymore? disconnect is expected, it's the behavior of our Deriv API, if you send an invalid JSON connection will be closed by the server. But after disconnecting, you should be able to run the program one more time and connect again.
```
root@9b6dc6132768:/home# ./wsget -u "wss://ws.binaryws.com/websockets/v3?app_id=1"
Connection Mode: Press ESC to enter Request mode
Request Mode: Type your API request and press Ctrl+S to send it. Press ESC to cancel request
fsdfsd

Connection Mode: Press ESC to enter Request mode
fsdfsd

2023/10/23 12:24:44 Fail to read from WS connection:EOF
root@9b6dc6132768:/home# 
```

**Comment by ksysoev** [comment]
Managed to reproduce the problem in bash, strange that zsh didn't face this issue. Let me try to fix it.
